---
# tasks file for nagiosmain
- name: Download and Extract Nagios Core
  unarchive:
    src: https://assets.nagios.com/downloads/nagioscore/releases/nagios-4.4.5.tar.gz
    dest: /tmp
    copy: no

- name: Configure Nagios within ubuntu
  command: ./configure --with-nagios-group=nagcmd --with-command-group=nagcmd --with-httpd_conf=/etc/apache2/sites-enabled
  args:
    chdir: /tmp/nagios-4.4.5

- name: Compile Nagios make clean
  make:
    chdir: /tmp/nagios-4.4.5
    target: clean

- name: Compile Nagios make all
  make:
    target: all
    chdir: /tmp/nagios-4.4.5

- name: Compile Nagios make install
  make:
    target: install
    chdir: /tmp/nagios-4.4.5

- name: Compile Nagios make install-init
  make:
    target: install-init
    chdir: /tmp/nagios-4.4.5

- name: Compile Nagios make install-config
  make:
    target: install-config
    chdir: /tmp/nagios-4.4.5
